config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :meter_readings

  resources :trackings

  resources :blogs

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/meter_reading.rb
class MeterReading < ActiveRecord::Base
end

app/controllers/meter_readings_controller.rb
class MeterReadingsController < ApplicationController
  before_action :set_meter_reading, only: [:show, :edit, :update, :destroy]

  # GET /meter_readings
  # GET /meter_readings.json
  def index
    @meter_readings = MeterReading.all
  end

  # GET /meter_readings/1
  # GET /meter_readings/1.json
  def show
  end

  # GET /meter_readings/new
  def new
    @meter_reading = MeterReading.new
  end

  # GET /meter_readings/1/edit
  def edit
  end

  # POST /meter_readings
  # POST /meter_readings.json
  def create
    @meter_reading = MeterReading.new(meter_reading_params)

    respond_to do |format|
      if @meter_reading.save
        format.html { redirect_to @meter_reading, notice: 'Meter reading was successfully created.' }
        format.json { render :show, status: :created, location: @meter_reading }
      else
        format.html { render :new }
        format.json { render json: @meter_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meter_readings/1
  # PATCH/PUT /meter_readings/1.json
  def update
    respond_to do |format|
      if @meter_reading.update(meter_reading_params)
        format.html { redirect_to @meter_reading, notice: 'Meter reading was successfully updated.' }
        format.json { render :show, status: :ok, location: @meter_reading }
      else
        format.html { render :edit }
        format.json { render json: @meter_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meter_readings/1
  # DELETE /meter_readings/1.json
  def destroy
    @meter_reading.destroy
    respond_to do |format|
      format.html { redirect_to meter_readings_url, notice: 'Meter reading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meter_reading
      @meter_reading = MeterReading.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meter_reading_params
      params.require(:meter_reading).permit(:value, :read_at, :unit)
    end
end

app/helpers/meter_readings_helper.rb
module MeterReadingsHelper
end

app/views/meter_readings/_form.html.erb
<%= form_for @meter_reading, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :value, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :value, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :read_at, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :read_at, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :unit, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :unit, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  meter_readings_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/meter_readings/edit.html.erb
<%- model_class = MeterReading -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => MeterReading %></h1>
</div>
<%= render :partial => 'form' %>

app/views/meter_readings/index.html.erb
<%- model_class = MeterReading -%>
<div class="page-header">
  <h1><%=t '.title', :default => MeterReading %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:read_at) %></th>
      <th><%= model_class.human_attribute_name(:unit) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @meter_readings.each do |meter_reading| %>
      <tr>
        <td><%= meter_reading.id %></td>
        <td><%= meter_reading.value %></td>
        <td><%= meter_reading.read_at %></td>
        <td><%= meter_reading.unit %></td>
        <td><%=l meter_reading.created_at, format: :long %></td>
        <td>
          <%= link_to meter_reading_path(meter_reading), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to meter_reading_path(meter_reading), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_meter_reading_path,
            :class => 'btn btn-primary' %>

app/views/meter_readings/new.html.erb
<%- model_class = MeterReading -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => MeterReading %></h1>
</div>
<%= render :partial => 'form' %>

app/views/meter_readings/show.html.erb
<%- model_class = MeterReading -%>
<div class="page-header">
  <h1><%=t '.title', :default => MeterReading %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:value) %></dt>
      <dd><pre class="prettyprint"><%= @meter_reading.value %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:read_at) %></dt>
      <dd><pre class="prettyprint"><%= @meter_reading.read_at %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:unit) %></dt>
      <dd><pre class="prettyprint"><%= @meter_reading.unit %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              meter_readings_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_meter_reading_path(@meter_reading), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              meter_reading_path(@meter_reading),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>